<template>
  <div class="movie-listing">
    <perfect-scrollbar>
      <Movie-Card v-for="(item, index) in 32" :key="index" />
    </perfect-scrollbar>
  </div>
</template>

<script>
import { PerfectScrollbar } from 'vue2-perfect-scrollbar';
import MovieCard from '@/components/MovieCard.vue';

export default {
  components: {
    PerfectScrollbar,
    MovieCard,
  },
};
</script>

<style lang="stylus" scoped>
.movie-listing {
  flex-grow: 1;
  height: 70vh;
  border: solid thin orange;

  .ps {
    /* .ps being the default classname generated by perfect-scrollbar */
    /* component requires a div as parent container */
    position: relative;
    display: grid;
    gap: 0.7rem 2rem;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    // add 30 px to grid height to account for text underneath
    grid-auto-rows: 200px;
    width: 100%;
    height: 100%;
    // height: 70vh;
    padding: 0 2em;
    background: var(--bg-color--primary);
  }
}
</style>
